import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'nl' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  nl: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'Over ons',
    'nav.services': 'Diensten',
    'nav.pricing': 'Prijzen',
    'nav.process': 'Werkwijze',
    'nav.contact': 'Contact',
    'nav.login': 'Inloggen',
    'nav.signup': 'Account aanmaken',
    'nav.dashboard': 'Dashboard',
    'nav.admin': 'Admin',
    'nav.logout': 'Uitloggen',
    
    // Hero
    'hero.title': 'Varexo - Full-stack Webdevelopment',
    'hero.subtitle': 'Wij bouwen professionele websites en software voor jouw bedrijf',
    'hero.cta': 'Bekijk onze diensten',
    
    // Services
    'services.title': 'Onze Diensten',
    'services.webdev': 'Webdevelopment',
    'services.webdev.desc': 'Professionele websites en webapplicaties op maat',
    'services.software': 'Software Development',
    'services.software.desc': 'Maatwerk software voor jouw bedrijf',
    'services.maintenance': 'Onderhoud & Support',
    'services.maintenance.desc': 'Continue onderhoud en technische support',
    
    // Homepage - Hero
    'home.hero.title': 'Wij bouwen websites die klanten',
    'home.hero.titleHighlight': 'opleveren.',
    'home.hero.subtitle': 'Professionele websites, webdevelopment en social media beheer voor ondernemers die willen groeien.',
    'home.hero.cta.primary': 'Vraag een gratis offerte aan',
    'home.hero.cta.secondary': 'Hoe wij werken',
    
    // Homepage - Tech Stack
    'home.techStack.label': 'Onze tech stack',
    
    // Homepage - Services
    'home.services.tag': '<services>',
    'home.services.title': 'Wat we doen',
    'home.services.subtitle': 'Full-stack oplossingen van concept tot deployment',
    'home.services.webdesign': 'Webdesign',
    'home.services.webdesign.desc': 'Pixel-perfect designs die converteren',
    'home.services.webdev': 'Webdevelopment',
    'home.services.webdev.desc': 'Clean code, snelle performance',
    'home.services.social': 'Social Media',
    'home.services.social.desc': 'Groei jouw bereik en engagement',
    'home.services.hosting': 'Hosting & DevOps',
    'home.services.hosting.desc': '99.9% uptime, razendsnelle servers',
    'home.services.closingTag': '</services>',
    
    // Homepage - Stats
    'home.stats.clients': 'Tevreden Klanten',
    'home.stats.projects': 'Projecten',
    'home.stats.uptime': 'Uptime',
    'home.stats.support': 'Support',
    
    // Homepage - Why Choose Us
    'home.why.tag': '// why-varexo',
    'home.why.title': 'Waarom Varexo',
    'home.why.fast': 'Snelle levering',
    'home.why.fast.desc': 'Agile development, snelle iteraties',
    'home.why.affordable': 'Betaalbaar',
    'home.why.affordable.desc': 'Transparante fixed-price pakketten',
    'home.why.personal': 'Persoonlijk',
    'home.why.personal.desc': 'Dedicated team, direct contact',
    'home.why.results': 'Resultaat gericht',
    'home.why.results.desc': 'Data-driven, focus op conversie',
    
    // Homepage - CTA
    'home.cta.tag': '$ varexo --start-project',
    'home.cta.title': 'Klaar om te deployen?',
    'home.cta.subtitle': 'Laten we jouw idee omzetten naar een snelle, schaalbare en professionele website.',
    'home.cta.button': 'Start nu',
    
    // Services Page
    'services.page.tag': '// what-we-build',
    'services.page.title': 'Onze Diensten',
    'services.page.subtitle': 'Van pixel-perfect design tot production-ready code',
    'services.page.moreInfo': 'Meer informatie →',
    'services.page.cta.title': 'Welke dienst past bij jou?',
    'services.page.cta.desc': 'Neem contact met ons op voor een vrijblijvend adviesgesprek. We helpen je graag met het kiezen van de juiste oplossing voor jouw bedrijf.',
    'services.page.cta.button': 'Vraag Offerte Aan',
    
    // Pricing Page
    'pricing.tag': '$ cat pricing_strategy.json',
    'pricing.title': 'Complete Website Pakketten',
    'pricing.subtitle': 'Transparante prijzen met maandelijkse garantie en 24/7 support. Geen verborgen kosten.',
    'pricing.basic.title': 'Basic',
    'pricing.pro.title': 'Pro',
    'pricing.premium.title': 'Premium',
    'pricing.onetime': 'eenmalig',
    'pricing.month': '/maand',
    'pricing.perYear': '/jaar',
    'pricing.choose': 'Kies',
    'pricing.guarantees.title': 'Onze Garanties',
    'pricing.cta.title': 'Niet zeker welk pakket?',
    'pricing.cta.button': 'Vraag Advies',
    'pricing.budget.title': 'Werken binnen uw budget',
    'pricing.budget.button': 'Neem contact op',
    
    // Log types
    'log.milestone': 'Mijlpaal',
    'log.feature': 'Nieuwe functie',
    'log.bugfix': 'Bugfix',
    'log.design': 'Design',
    'log.deployment': 'Deployment',
    'log.update': 'Update',
    
    // Auth
    'auth.login': 'Inloggen',
    'auth.signup': 'Account aanmaken',
    'auth.loginTitle': 'Klant Portaal',
    'auth.loginSubtitle': 'Log in om je projecten en facturen te bekijken',
    'auth.googleLogin': 'Inloggen met Google',
    'auth.email': 'Email adres',
    'auth.emailPlaceholder': 'jouw@email.nl',
    'auth.password': 'Wachtwoord',
    'auth.forgotPassword': 'Wachtwoord vergeten?',
    'auth.noAccount': 'Nog geen account?',
    'auth.hasAccount': 'Al een account?',
    'auth.createAccount': 'Maak een account aan',
    'auth.loginHere': 'Log hier in',
    'auth.errors.passwordMismatch': 'Wachtwoorden komen niet overeen',
    'auth.errors.passwordLength': 'Wachtwoord moet minimaal 6 tekens bevatten',
    'auth.errors.registrationFailed': 'Registratie mislukt. Probeer het opnieuw.',
    'auth.errors.googleSignupFailed': 'Google registratie mislukt. Probeer het opnieuw.',
    'auth.signupTitle': 'Maak een account',
    'auth.signupSubtitle': 'Registreer om toegang te krijgen tot het klantportaal',
    'auth.name': 'Naam',
    'auth.namePlaceholder': 'Jouw naam',
    'auth.passwordPlaceholder': 'Minimaal 6 tekens',
    'auth.confirmPassword': 'Bevestig wachtwoord',
    'auth.confirmPasswordPlaceholder': 'Herhaal wachtwoord',
    'auth.registering': 'Registreren...',
    'auth.signupButton': 'Account aanmaken',
    'auth.errors.accountNotFound': 'Account bestaat niet. Maak eerst een account aan via "Gratis Account Aanmaken".',
    'auth.errors.googleLoginFailed': 'Google login mislukt. Probeer het opnieuw.',
    'auth.rememberMe': 'Onthoud mij',
    'auth.orWithEmail': 'Of met e-mail',
    'auth.forgotPasswordTitle': 'Wachtwoord vergeten?',
    'auth.forgotPasswordSubtitle': 'Vul je email adres in en we sturen je een reset link.',
    'auth.enterEmail': 'Vul je email adres in',
    'auth.resetLinkSent': 'Als dit email adres bestaat in ons systeem, ontvang je een wachtwoord reset link.',
    'auth.sending': 'Versturen...',
    'auth.sendResetLink': 'Reset link versturen',
    'auth.or': 'of',
    'auth.resetPasswordTitle': 'Nieuw wachtwoord instellen',
    'auth.resetPasswordSubtitle': 'Kies een sterk wachtwoord voor je account.',
    'auth.newPassword': 'Nieuw wachtwoord',
    'auth.invalidResetLink': 'Ongeldige of verlopen reset link. Vraag een nieuwe wachtwoord reset aan.',
    'auth.invalidResetToken': 'Ongeldige reset token',
    'auth.passwordChanged': 'Wachtwoord succesvol gewijzigd! Je wordt doorverwezen naar de login pagina...',
    'auth.resetFailed': 'Wachtwoord reset mislukt. De link is mogelijk verlopen of al gebruikt.',
    'auth.requestNewLink': 'Nieuwe reset link aanvragen →',
    'auth.changing': 'Bezig...',
    'auth.changePassword': 'Wachtwoord wijzigen',
    
    // Dashboard
    'dashboard.title': 'Mijn Dashboard',
    'dashboard.welcome': 'Welkom terug',
    'dashboard.projects': 'Mijn Projecten',
    'dashboard.invoices': 'Mijn Facturen',
    'dashboard.settings': 'Instellingen',
    'dashboard.noProjects': 'Nog geen projecten',
    'dashboard.noInvoices': 'Nog geen facturen',
    'dashboard.subscription': 'Abonnement',
    'dashboard.noSubscription': 'Geen abonnement',
    'dashboard.activeProjects': 'Actieve Projecten',
    'dashboard.completedProjects': 'Voltooide Projecten',
    'dashboard.pendingInvoices': 'Openstaande Facturen',
    'dashboard.adminWillCreate': 'De admin zal projecten voor je aanmaken',
    'dashboard.loading': 'Laden...',
    'dashboard.invoice': 'Factuur',
    'dashboard.project': 'Project',
    'dashboard.amount': 'Bedrag',
    'dashboard.status': 'Status',
    'dashboard.dueDate': 'Vervaldatum',
    'dashboard.action': 'Actie',
    'dashboard.invoiceStatus.draft': 'Concept',
    'dashboard.invoiceStatus.sent': 'Verzonden',
    'dashboard.invoiceStatus.paid': 'Betaald',
    'dashboard.invoiceStatus.overdue': 'Te laat',
    'dashboard.progress': 'Voortgang',
    'dashboard.deadline': 'Deadline',
    'dashboard.budget': 'Budget',
    'dashboard.projectUpdates': 'Project Updates & Logs',
    'dashboard.loadingUpdates': 'Updates laden...',
    'dashboard.noUpdates': 'Nog geen updates voor dit project.',
    'dashboard.adminWillPostUpdates': 'De admin zal hier updates plaatsen.',
    'dashboard.by': 'Door:',
    'dashboard.questionsCall': 'Vragen? Bel ons:',
    
    // Admin
    'admin.title': 'Admin Dashboard',
    'admin.customers': 'Klanten',
    'admin.customer': 'Klant',
    'admin.company': 'Bedrijf',
    'admin.subscription': 'Abonnement',
    'admin.actions': 'Acties',
    'admin.projects': 'Projecten',
    'admin.invoices': 'Facturen',
    'admin.invoice': 'Factuur',
    'admin.finance': 'Financiën',
    'admin.expenses': 'Kosten',
    'admin.messages': 'Berichten',
    'admin.settings': 'Instellingen',
    'admin.stats': 'Statistieken',
    'admin.totalCustomers': 'Klanten',
    'admin.totalProjects': 'Projecten',
    'admin.totalRevenue': 'Omzet',
    'admin.pendingInvoices': 'Openstaand',
    'admin.view': 'Website',
    'admin.logs': 'Logs',
    'admin.edit': 'Bewerken',
    'admin.delete': 'Verwijderen',
    'admin.description': 'Beschrijving',
    'admin.deadline': 'Deadline',
    'admin.budget': 'Budget',
    'admin.websiteUrl': 'Website URL',
    'admin.addNewUpdate': 'NIEUWE UPDATE TOEVOEGEN',
    'admin.updateTitle': 'Update titel',
    'admin.updateDescPlaceholder': 'Beschrijving van wat er is gedaan...',
    'admin.updatesAndLogs': 'UPDATES & LOGS',
    'admin.status': 'Status',
    
    // Profile Page
    'profile.loading': 'Laden...',
    'profile.breadcrumb.dashboard': 'Dashboard',
    'profile.breadcrumb.profile': 'Profiel',
    'profile.title': 'Mijn Profiel',
    'profile.subtitle': 'Beheer je accountgegevens en wachtwoord',
    'profile.personalInfo': 'Persoonlijke gegevens',
    'profile.name': 'Naam',
    'profile.email': 'E-mailadres',
    'profile.emailHelp': 'E-mail kan niet worden gewijzigd',
    'profile.phone': 'Telefoonnummer',
    'profile.company': 'Bedrijfsnaam',
    'profile.companyPlaceholder': 'Jouw bedrijf',
    'profile.phonePlaceholder': '+31 6 12345678',
    'profile.addressPlaceholder': 'Straatnaam 123',
    'profile.cityPlaceholder': 'Amsterdam',
    'profile.address': 'Adres',
    'profile.city': 'Plaats',
    'profile.password.title': 'Wachtwoord wijzigen',
    'profile.password.change': 'Wachtwoord wijzigen →',
    'profile.password.current': 'Huidig wachtwoord',
    'profile.password.new': 'Nieuw wachtwoord',
    'profile.password.confirm': 'Bevestig nieuw wachtwoord',
    'profile.password.minLength': 'Minimaal 6 tekens',
    'profile.password.updating': 'Bezig...',
    'profile.password.update': 'Wijzigen',
    'profile.password.cancel': 'Annuleren',
    'profile.quickLinks': 'Snelle links',
    'profile.googleAccount': 'Google account',
    'profile.password.success': 'Wachtwoord succesvol gewijzigd!',
    'profile.errors.passwordMatch': 'Nieuwe wachtwoorden komen niet overeen',
    'profile.errors.passwordLength': 'Wachtwoord moet minimaal 6 tekens bevatten',
    'profile.errors.passwordChangeFailed': 'Wachtwoord wijzigen mislukt. Controleer je huidige wachtwoord.',
    
    // Contact Page
    'contact.tag': '$ request_quote.sh',
    'contact.title': 'Gratis Offerte Aanvragen',
    'contact.subtitle': 'Vertel ons over uw project en ontvang binnen 24 uur een vrijblijvende offerte',
    'contact.form.title': 'Project Details',
    'contact.form.name': 'Naam',
    'contact.form.email': 'Email',
    'contact.form.phone': 'Telefoon',
    'contact.form.company': 'Bedrijf',
    'contact.form.projectType': 'Type Project',
    'contact.form.projectType.placeholder': 'Kies een type project',
    'contact.form.projectType.website': 'Website',
    'contact.form.projectType.webshop': 'Webshop',
    'contact.form.projectType.social': 'Social Media Management',
    'contact.form.projectType.seo': 'SEO Optimalisatie',
    'contact.form.projectType.custom': 'Maatwerk Software',
    'contact.form.projectType.maintenance': 'Website Onderhoud',
    'contact.form.projectType.other': 'Anders',
    'contact.form.description': 'Project Beschrijving',
    'contact.form.description.placeholder': 'Beschrijf uw project, wensen en doelen...',
    'contact.form.submit': 'Offerte Aanvragen',
    'contact.form.sending': 'Versturen...',
    'contact.whatsapp.title': 'Direct Contact',
    'contact.whatsapp.desc': 'Liever direct contact? Stuur ons een bericht via WhatsApp voor een snelle respons!',
    'contact.whatsapp.button': 'Stuur WhatsApp',
    'contact.info.title': 'Contact Info',
    'contact.info.response': 'Binnen 24 uur reactie',
    'contact.why.title': 'Waarom Varexo?',
    'contact.why.quote': 'Gratis offerte binnen 24 uur',
    'contact.why.pricing': 'Vaste prijzen, geen verrassingen',
    'contact.why.uptime': '24/7 uptime garantie',
    'contact.why.personal': 'Persoonlijke aanpak',
    'contact.process.title': 'Hoe Werkt Het?',
    'contact.process.step1.title': 'Offerte Aanvragen',
    'contact.process.step1.desc': 'Vul het formulier in of stuur een WhatsApp bericht',
    'contact.process.step2.title': 'Contact',
    'contact.process.step2.desc': 'We nemen binnen 24 uur contact voor details',
    'contact.process.step3.title': 'Offerte',
    'contact.process.step3.desc': 'U ontvangt een vrijblijvende offerte',
    'contact.process.step4.title': 'Start Project',
    'contact.process.step4.desc': 'Akkoord? Dan starten we direct met uw project',
    
    // Profile Settings
    'settings.title': 'Instellingen',
    'settings.profile': 'Profiel',
    'settings.displayName': 'Weergavenaam',
    'settings.phone': 'Telefoon',
    'settings.company': 'Bedrijf',
    'settings.emailNotifications': 'Email notificaties',
    'settings.emailNotifications.desc': 'Ontvang emails over project updates en facturen',
    'settings.language': 'Taal',
    'settings.language.desc': 'Kies je voorkeurstaal',
    'settings.save': 'Opslaan',
    'settings.saving': 'Opslaan...',
    'settings.saved': 'Opgeslagen!',
    
    // Email Language Preference
    'email.language.title': 'Email taal',
    'email.language.desc': 'Ontvang emails in je voorkeurstaal',
    'email.language.nl': 'Nederlands',
    'email.language.en': 'Engels',
    
    // Common
    'common.loading': 'Laden...',
    'common.save': 'Opslaan',
    'common.cancel': 'Annuleren',
    'common.delete': 'Verwijderen',
    'common.deleting': 'Verwijderen...',
    'common.edit': 'Bewerken',
    'common.create': 'Aanmaken',
    'common.refresh': 'Verversen',
    'common.search': 'Zoeken',
    'common.filter': 'Filteren',
    'common.all': 'Alle',
    'common.status': 'Status',
    'common.date': 'Datum',
    'common.amount': 'Bedrag',
    'common.actions': 'Acties',
    'common.view': 'Bekijken',
    'common.download': 'Downloaden',
    'common.send': 'Versturen',
    'common.close': 'Sluiten',
    'common.back': 'Terug',
    'common.next': 'Volgende',
    'common.submit': 'Verzenden',
    'common.success': 'Succes!',
    'common.error': 'Er is een fout opgetreden',
    'common.confirm': 'Bevestigen',
    'common.yes': 'Ja',
    'common.no': 'Nee',
    'common.on': 'Aan',
    'common.off': 'Uit',
    'common.progress': 'Voortgang',
    'common.paid': 'Betaald',
    'common.open': 'Open',
    'common.overdue': 'Achterstallig',
    'common.active': 'Actief',
    'common.paused': 'Gepauzeerd',
    'common.planning': 'Planning',
    'common.completed': 'Voltooid',
    'common.monthly': 'Maandelijks',
    'common.yearly': 'Jaarlijks',
    'common.one-time': 'Eenmalig',
    'common.type': 'Type',
    'common.frequency': 'Frequentie',
    'common.optional': 'optioneel',
    'common.adding': 'Toevoegen...',
    'common.saving': 'Opslaan...',
    'common.creating': 'Aanmaken...',
    'common.add': 'Toevoegen',
    
    // Footer
    'footer.navigation': 'Navigatie',
    'footer.legal': 'Juridisch',
    'footer.contact': 'Contact',
    'footer.rights': 'Alle rechten voorbehouden.',
    'footer.description': 'Wij bouwen snelle, schaalbare en professionele websites voor ondernemers.',
    'footer.terms': 'Algemene Voorwaarden',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.cookiePolicy': 'Cookie Policy',
    'footer.whatsapp': 'WhatsApp',
    'footer.kvk': 'KvK',
    'footer.btw': 'BTW',
    'footer.poweredBy': 'Medemogelijk gemaakt door',
    
    // WhatsApp
    'whatsapp.title': 'Varexo op WhatsApp',
    'whatsapp.response': 'Meestal binnen 1 uur reactie',
    'whatsapp.quote': 'Ik wil graag een offerte',
    'whatsapp.quoteMessage': 'Hallo! Ik wil graag een offerte aanvragen voor een website.',
    'whatsapp.services': 'Vraag over diensten',
    'whatsapp.servicesMessage': 'Hallo! Ik heb een vraag over jullie diensten.',
    'whatsapp.support': 'Support nodig',
    'whatsapp.supportMessage': 'Hallo! Ik heb support nodig voor mijn website.',
    'whatsapp.general': 'Algemene vraag',
    'whatsapp.generalMessage': 'Hallo! Ik heb een vraag.',
    
    // Help Widget
    'help.title': 'Hulp nodig?',
    'help.subtitle': 'Veelgestelde vragen',
    'help.question1': 'Wat kost een website?',
    'help.answer1': 'Onze pakketten starten vanaf €399 voor een basic website. Bekijk onze prijzenpagina voor alle opties.',
    'help.question2': 'Hoe lang duurt het?',
    'help.answer2': 'Een basic website is binnen 1-2 weken klaar. Maatwerk projecten duren 4-8 weken, afhankelijk van de complexiteit.',
    'help.question3': 'Kan ik mijn site zelf beheren?',
    'help.answer3': 'Ja! We leveren altijd een gebruiksvriendelijk CMS mee en geven uitleg over het beheer van je website.',
    'help.question4': 'Bieden jullie hosting aan?',
    'help.answer4': 'Ja, we bieden snelle en betrouwbare hosting vanaf €20 per maand, inclusief SSL, back-ups en monitoring.',
    'help.question5': 'Hoe kan ik contact opnemen?',
    'help.answer5': 'Via WhatsApp (+31 6 36075966), e-mail (info@varexo.nl) of het contactformulier op onze website.',
    'help.askQuestion': 'Stel een andere vraag',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.pricing': 'Pricing',
    'nav.process': 'Process',
    'nav.contact': 'Contact',
    'nav.login': 'Login',
    'nav.signup': 'Sign Up',
    'nav.dashboard': 'Dashboard',
    'nav.admin': 'Admin',
    'nav.logout': 'Logout',
    
    // Hero
    'hero.title': 'Varexo - Full-stack Webdevelopment',
    'hero.subtitle': 'We build professional websites and software for your business',
    'hero.cta': 'View our services',
    
    // Services
    'services.title': 'Our Services',
    'services.webdev': 'Web Development',
    'services.webdev.desc': 'Professional websites and web applications tailored to your needs',
    'services.software': 'Software Development',
    'services.software.desc': 'Custom software solutions for your business',
    'services.maintenance': 'Maintenance & Support',
    'services.maintenance.desc': 'Continuous maintenance and technical support',
    
    // Homepage - Hero
    'home.hero.title': 'We build websites that',
    'home.hero.titleHighlight': 'deliver customers.',
    'home.hero.subtitle': 'Professional websites, web development and social media management for entrepreneurs who want to grow.',
    'home.hero.cta.primary': 'Request a free quote',
    'home.hero.cta.secondary': 'How we work',
    
    // Homepage - Tech Stack
    'home.techStack.label': 'Our tech stack',
    
    // Homepage - Services
    'home.services.tag': '<services>',
    'home.services.title': 'What we do',
    'home.services.subtitle': 'Full-stack solutions from concept to deployment',
    'home.services.webdesign': 'Web Design',
    'home.services.webdesign.desc': 'Pixel-perfect designs that convert',
    'home.services.webdev': 'Web Development',
    'home.services.webdev.desc': 'Clean code, fast performance',
    'home.services.social': 'Social Media',
    'home.services.social.desc': 'Grow your reach and engagement',
    'home.services.hosting': 'Hosting & DevOps',
    'home.services.hosting.desc': '99.9% uptime, lightning-fast servers',
    'home.services.closingTag': '</services>',
    
    // Homepage - Stats
    'home.stats.clients': 'Happy Clients',
    'home.stats.projects': 'Projects',
    'home.stats.uptime': 'Uptime',
    'home.stats.support': 'Support',
    
    // Homepage - Why Choose Us
    'home.why.tag': '// why-varexo',
    'home.why.title': 'Why Varexo',
    'home.why.fast': 'Fast Delivery',
    'home.why.fast.desc': 'Agile development, quick iterations',
    'home.why.affordable': 'Affordable',
    'home.why.affordable.desc': 'Transparent fixed-price packages',
    'home.why.personal': 'Personal',
    'home.why.personal.desc': 'Dedicated team, direct contact',
    'home.why.results': 'Results Driven',
    'home.why.results.desc': 'Data-driven, focused on conversion',
    
    // Homepage - CTA
    'home.cta.tag': '$ varexo --start-project',
    'home.cta.title': 'Ready to deploy?',
    'home.cta.subtitle': "Let's turn your idea into a fast, scalable and professional website.",
    'home.cta.button': 'Start now',
    
    // Services Page
    'services.page.tag': '// what-we-build',
    'services.page.title': 'Our Services',
    'services.page.subtitle': 'From pixel-perfect design to production-ready code',
    'services.page.moreInfo': 'More information →',
    'services.page.cta.title': 'Which service fits you?',
    'services.page.cta.desc': 'Contact us for a no-obligation consultation. We are happy to help you choose the right solution for your business.',
    'services.page.cta.button': 'Request a Quote',
    
    // Pricing Page
    'pricing.tag': '$ cat pricing_strategy.json',
    'pricing.title': 'Complete Website Packages',
    'pricing.subtitle': 'Transparent prices with monthly guarantee and 24/7 support. No hidden costs.',
    'pricing.basic.title': 'Basic',
    'pricing.pro.title': 'Pro',
    'pricing.premium.title': 'Premium',
    'pricing.onetime': 'one-time',
    'pricing.month': '/month',
    'pricing.perYear': '/year',
    'pricing.choose': 'Choose',
    'pricing.guarantees.title': 'Our Guarantees',
    'pricing.cta.title': 'Not sure which package?',
    'pricing.cta.button': 'Request Advice',
    'pricing.budget.title': 'Work within your budget',
    'pricing.budget.button': 'Contact us',
    
    // Log types
    'log.milestone': 'Milestone',
    'log.feature': 'New Feature',
    'log.bugfix': 'Bugfix',
    'log.design': 'Design',
    'log.deployment': 'Deployment',
    'log.update': 'Update',
    
    // Auth
    'auth.login': 'Login',
    'auth.signup': 'Sign Up',
    'auth.loginTitle': 'Customer Portal',
    'auth.loginSubtitle': 'Log in to view your projects and invoices',
    'auth.googleLogin': 'Login with Google',
    'auth.email': 'Email address',
    'auth.emailPlaceholder': 'your@email.com',
    'auth.password': 'Password',
    'auth.forgotPassword': 'Forgot password?',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'auth.createAccount': 'Create an account',
    'auth.loginHere': 'Login here',
    'auth.errors.passwordMismatch': 'Passwords do not match',
    'auth.errors.passwordLength': 'Password must contain at least 6 characters',
    'auth.errors.registrationFailed': 'Registration failed. Please try again.',
    'auth.errors.googleSignupFailed': 'Google registration failed. Please try again.',
    'auth.signupTitle': 'Create an account',
    'auth.signupSubtitle': 'Register to access the customer portal',
    'auth.name': 'Name',
    'auth.namePlaceholder': 'Your name',
    'auth.passwordPlaceholder': 'At least 6 characters',
    'auth.confirmPassword': 'Confirm password',
    'auth.confirmPasswordPlaceholder': 'Repeat password',
    'auth.registering': 'Registering...',
    'auth.signupButton': 'Create Account',
    'auth.forgotPasswordTitle': 'Forgot password?',
    'auth.forgotPasswordSubtitle': 'Enter your email address and we will send you a reset link.',
    'auth.enterEmail': 'Enter your email address',
    'auth.resetLinkSent': 'If this email address exists in our system, you will receive a password reset link.',
    'auth.sending': 'Sending...',
    'auth.sendResetLink': 'Send reset link',
    'auth.or': 'or',
    'auth.resetPasswordTitle': 'Set new password',
    'auth.resetPasswordSubtitle': 'Choose a strong password for your account.',
    'auth.newPassword': 'New password',
    'auth.invalidResetLink': 'Invalid or expired reset link. Request a new password reset.',
    'auth.invalidResetToken': 'Invalid reset token',
    'auth.passwordChanged': 'Password changed successfully! You will be redirected to the login page...',
    'auth.resetFailed': 'Password reset failed. The link may have expired or already been used.',
    'auth.requestNewLink': 'Request new reset link →',
    'auth.changing': 'Changing...',
    'auth.changePassword': 'Change Password',
    'auth.errors.accountNotFound': 'Account does not exist. First create an account via "Create Free Account".',
    'auth.errors.googleLoginFailed': 'Google login failed. Please try again.',
    'auth.rememberMe': 'Remember me',
    'auth.orWithEmail': 'Or with email',
    
    // Dashboard
    'dashboard.title': 'My Dashboard',
    'dashboard.welcome': 'Welcome back',
    'dashboard.projects': 'My Projects',
    'dashboard.invoices': 'My Invoices',
    'dashboard.settings': 'Settings',
    'dashboard.noProjects': 'No projects yet',
    'dashboard.noInvoices': 'No invoices yet',
    'dashboard.subscription': 'Subscription',
    'dashboard.noSubscription': 'No subscription',
    'dashboard.activeProjects': 'Active Projects',
    'dashboard.completedProjects': 'Completed Projects',
    'dashboard.pendingInvoices': 'Pending Invoices',
    'dashboard.adminWillCreate': 'The admin will create projects for you',
    'dashboard.loading': 'Loading...',
    'dashboard.invoice': 'Invoice',
    'dashboard.project': 'Project',
    'dashboard.amount': 'Amount',
    'dashboard.status': 'Status',
    'dashboard.dueDate': 'Due Date',
    'dashboard.action': 'Action',
    'dashboard.invoiceStatus.draft': 'Draft',
    'dashboard.invoiceStatus.sent': 'Sent',
    'dashboard.invoiceStatus.paid': 'Paid',
    'dashboard.invoiceStatus.overdue': 'Overdue',
    'dashboard.progress': 'Progress',
    'dashboard.deadline': 'Deadline',
    'dashboard.budget': 'Budget',
    'dashboard.projectUpdates': 'Project Updates & Logs',
    'dashboard.loadingUpdates': 'Loading updates...',
    'dashboard.noUpdates': 'No updates for this project yet.',
    'dashboard.adminWillPostUpdates': 'The admin will post updates here.',
    'dashboard.by': 'By:',
    'dashboard.questionsCall': 'Questions? Call us:',
    
    // Admin
    'admin.title': 'Admin Dashboard',
    'admin.customers': 'Customers',
    'admin.customer': 'Customer',
    'admin.company': 'Company',
    'admin.subscription': 'Subscription',
    'admin.actions': 'Actions',
    'admin.projects': 'Projects',
    'admin.invoices': 'Invoices',
    'admin.invoice': 'Invoice',
    'admin.finance': 'Finance',
    'admin.expenses': 'Expenses',
    'admin.messages': 'Messages',
    'admin.settings': 'Settings',
    'admin.stats': 'Statistics',
    'admin.totalCustomers': 'Customers',
    'admin.totalProjects': 'Projects',
    'admin.totalRevenue': 'Revenue',
    'admin.pendingInvoices': 'Pending',
    'admin.view': 'Website',
    'admin.logs': 'Logs',
    'admin.edit': 'Edit',
    'admin.delete': 'Delete',
    'admin.description': 'Description',
    'admin.deadline': 'Deadline',
    'admin.budget': 'Budget',
    'admin.websiteUrl': 'Website URL',
    'admin.addNewUpdate': 'ADD NEW UPDATE',
    'admin.updateTitle': 'Update title',
    'admin.updateDescPlaceholder': 'Description of what was done...',
    'admin.updatesAndLogs': 'UPDATES & LOGS',
    'admin.status': 'Status',
    
    // Profile Page
    'profile.loading': 'Loading...',
    'profile.breadcrumb.dashboard': 'Dashboard',
    'profile.breadcrumb.profile': 'Profile',
    'profile.title': 'My Profile',
    'profile.subtitle': 'Manage your account details and password',
    'profile.personalInfo': 'Personal Information',
    'profile.name': 'Name',
    'profile.email': 'Email Address',
    'profile.emailHelp': 'Email cannot be changed',
    'profile.phone': 'Phone Number',
    'profile.company': 'Company Name',
    'profile.companyPlaceholder': 'Your company',
    'profile.phonePlaceholder': '+31 6 12345678',
    'profile.addressPlaceholder': 'Street 123',
    'profile.cityPlaceholder': 'Amsterdam',
    'profile.address': 'Address',
    'profile.city': 'City',
    'profile.password.title': 'Change Password',
    'profile.password.change': 'Change Password →',
    'profile.password.current': 'Current Password',
    'profile.password.new': 'New Password',
    'profile.password.confirm': 'Confirm New Password',
    'profile.password.minLength': 'At least 6 characters',
    'profile.password.updating': 'Updating...',
    'profile.password.update': 'Update',
    'profile.password.cancel': 'Cancel',
    'profile.quickLinks': 'Quick Links',
    'profile.googleAccount': 'Google account',
    'profile.password.success': 'Password changed successfully!',
    'profile.errors.passwordMatch': 'New passwords do not match',
    'profile.errors.passwordLength': 'Password must contain at least 6 characters',
    'profile.errors.passwordChangeFailed': 'Failed to change password. Check your current password.',
    
    // Contact Page
    'contact.tag': '$ request_quote.sh',
    'contact.title': 'Request Free Quote',
    'contact.subtitle': 'Tell us about your project and receive a no-obligation quote within 24 hours',
    'contact.form.title': 'Project Details',
    'contact.form.name': 'Name',
    'contact.form.email': 'Email',
    'contact.form.phone': 'Phone',
    'contact.form.company': 'Company',
    'contact.form.projectType': 'Project Type',
    'contact.form.projectType.placeholder': 'Choose a project type',
    'contact.form.projectType.website': 'Website',
    'contact.form.projectType.webshop': 'Webshop',
    'contact.form.projectType.social': 'Social Media Management',
    'contact.form.projectType.seo': 'SEO Optimization',
    'contact.form.projectType.custom': 'Custom Software',
    'contact.form.projectType.maintenance': 'Website Maintenance',
    'contact.form.projectType.other': 'Other',
    'contact.form.description': 'Project Description',
    'contact.form.description.placeholder': 'Describe your project, wishes and goals...',
    'contact.form.submit': 'Request Quote',
    'contact.form.sending': 'Sending...',
    'contact.whatsapp.title': 'Direct Contact',
    'contact.whatsapp.desc': 'Prefer direct contact? Send us a message via WhatsApp for a quick response!',
    'contact.whatsapp.button': 'Send WhatsApp',
    'contact.info.title': 'Contact Info',
    'contact.info.response': 'Response within 24 hours',
    'contact.why.title': 'Why Varexo?',
    'contact.why.quote': 'Free quote within 24 hours',
    'contact.why.pricing': 'Fixed prices, no surprises',
    'contact.why.uptime': '24/7 uptime guarantee',
    'contact.why.personal': 'Personal approach',
    'contact.process.title': 'How It Works?',
    'contact.process.step1.title': 'Request Quote',
    'contact.process.step1.desc': 'Fill in the form or send a WhatsApp message',
    'contact.process.step2.title': 'Contact',
    'contact.process.step2.desc': 'We will contact you within 24 hours for details',
    'contact.process.step3.title': 'Quote',
    'contact.process.step3.desc': 'You will receive a no-obligation quote',
    'contact.process.step4.title': 'Start Project',
    'contact.process.step4.desc': 'Agree? Then we start your project immediately',
    
    // Profile Settings
    'settings.title': 'Settings',
    'settings.profile': 'Profile',
    'settings.displayName': 'Display Name',
    'settings.phone': 'Phone',
    'settings.company': 'Company',
    'settings.emailNotifications': 'Email notifications',
    'settings.emailNotifications.desc': 'Receive emails about project updates and invoices',
    'settings.language': 'Language',
    'settings.language.desc': 'Choose your preferred language',
    'settings.save': 'Save',
    'settings.saving': 'Saving...',
    'settings.saved': 'Saved!',
    
    // Email Language Preference
    'email.language.title': 'Email language',
    'email.language.desc': 'Receive emails in your preferred language',
    'email.language.nl': 'Dutch',
    'email.language.en': 'English',
    
    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.deleting': 'Deleting...',
    'common.edit': 'Edit',
    'common.create': 'Create',
    'common.refresh': 'Refresh',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.all': 'All',
    'common.status': 'Status',
    'common.date': 'Date',
    'common.amount': 'Amount',
    'common.actions': 'Actions',
    'common.view': 'View',
    'common.download': 'Download',
    'common.send': 'Send',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.submit': 'Submit',
    'common.success': 'Success!',
    'common.error': 'An error occurred',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.on': 'On',
    'common.off': 'Off',
    'common.progress': 'Progress',
    'common.paid': 'Paid',
    'common.open': 'Open',
    'common.overdue': 'Overdue',
    'common.active': 'Active',
    'common.paused': 'Paused',
    'common.planning': 'Planning',
    'common.completed': 'Completed',
    'common.monthly': 'Monthly',
    'common.yearly': 'Yearly',
    'common.one-time': 'One-time',
    'common.type': 'Type',
    'common.frequency': 'Frequency',
    'common.optional': 'optional',
    'common.adding': 'Adding...',
    'common.saving': 'Saving...',
    'common.creating': 'Creating...',
    'common.add': 'Add',
    'common.socialMedia': 'Social Media',
    
    // Footer
    'footer.navigation': 'Navigation',
    'footer.legal': 'Legal',
    'footer.contact': 'Contact',
    'footer.rights': 'All rights reserved.',
    'footer.description': 'We build fast, scalable and professional websites for entrepreneurs.',
    'footer.terms': 'Terms & Conditions',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.cookiePolicy': 'Cookie Policy',
    'footer.whatsapp': 'WhatsApp',
    'footer.kvk': 'KvK',
    'footer.btw': 'VAT',
    'footer.poweredBy': 'Powered by',
    
    // WhatsApp
    'whatsapp.title': 'Varexo on WhatsApp',
    'whatsapp.response': 'Usually respond within 1 hour',
    'whatsapp.quote': 'I want a quote',
    'whatsapp.quoteMessage': 'Hello! I would like to request a quote for a website.',
    'whatsapp.services': 'Question about services',
    'whatsapp.servicesMessage': 'Hello! I have a question about your services.',
    'whatsapp.support': 'Need support',
    'whatsapp.supportMessage': 'Hello! I need support for my website.',
    'whatsapp.general': 'General question',
    'whatsapp.generalMessage': 'Hello! I have a question.',
    
    // Help Widget
    'help.title': 'Need help?',
    'help.subtitle': 'Frequently asked questions',
    'help.question1': 'What does a website cost?',
    'help.answer1': 'Our packages start from €399 for a basic website. View our pricing page for all options.',
    'help.question2': 'How long does it take?',
    'help.answer2': 'A basic website is ready within 1-2 weeks. Custom projects take 4-8 weeks, depending on complexity.',
    'help.question3': 'Can I manage my site myself?',
    'help.answer3': 'Yes! We always include a user-friendly CMS and provide explanation on managing your website.',
    'help.question4': 'Do you offer hosting?',
    'help.answer4': 'Yes, we offer fast and reliable hosting from €20 per month, including SSL, backups and monitoring.',
    'help.question5': 'How can I contact you?',
    'help.answer5': 'Via WhatsApp (+31 6 36075966), email (info@varexo.nl) or the contact form on our website.',
    'help.askQuestion': 'Ask another question',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  // Auto-detect language from domain
  const getDefaultLanguage = (): Language => {
    const domain = window.location.hostname;
    if (domain.includes('varexo.net')) return 'en';
    if (domain.includes('varexo.nl')) return 'nl';
    
    // Check stored preference
    const stored = localStorage.getItem('varexo-language') as Language;
    if (stored === 'nl' || stored === 'en') return stored;
    
    // Default to browser language
    const browserLang = navigator.language.toLowerCase();
    if (browserLang.startsWith('nl')) return 'nl';
    return 'en';
  };

  const [language, setLanguageState] = useState<Language>(getDefaultLanguage());

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('varexo-language', lang);
    // Update HTML lang attribute
    document.documentElement.lang = lang;
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['nl']] || key;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
